version: '3'
services:
  backend:
    image: 'ccr.ccs.tencentyun.com/desert/desert-backend:latest'
    container_name: 'desert-backend-web'
    ports:
     - "8000:8000"
    command:
      - cd /usr/app/
      - python3 manage.py makemigrations player
      - python3 manage.py makemigrations plot
      - python3 manage.py makemigrations song
      - python3 manage.py migrate
      - python3 manage.py collectstatic
      - python3 manage.py compilemessages
    depends_on:
      - 'redis'
      - 'db'
  redis:
    image: "redis:alpine"
    container_name: 'redis'
    ports:
     - "6379:6379"
  db:
    image: "mariadb:14.2"
    container_name: 'mariadb'
    volumes:
      - '/usr/mariadb:/usr/db/mariadb'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "desert"
      MYSQL_USER: "desert"
      MYSQL_PASSWORD: "Desert_internal_stuff_22"