version: '3'
services:
  backend:
    image: 'hkccr.ccs.tencentyun.com/desert/desert-backend-hongkong:latest'
    container_name: 'web'
    ports:
     - "8000:8000"
    security_opt:
      - label=type:container_runtime_t
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - 'redis'
      - 'db'
    command: >
      sh -c "python3 manage.py makemigrations player &&
             python3 manage.py makemigrations plot && 
             python3 manage.py makemigrations song &&
             python3 manage.py migrate &&
             rm -rf static
             python3 manage.py collectstatic && 
             python3 manage.py compilemessages && 
             gunicorn desert.wsgi -w 5 -k gevent -b 0.0.0.0:8000"
  redis:
    image: "redis:alpine"
    container_name: 'redis'
    ports:
     - "6379:6379"
    security_opt:
      - label=type:container_runtime_t
  db:
    image: "mariadb:10.8-rc"
    container_name: 'mariadb'
    volumes:
      - '/usr/mariadb:/usr/db/mariadb'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "desert"
      MYSQL_USER: "desert"
      MYSQL_PASSWORD: "Desert_internal_stuff_22"
    security_opt:
      - label=type:container_runtime_t