# Generated by Django 4.0.3 on 2022-03-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_stuff',
            field=models.BooleanField(default=False),
        ),
    ]
