# Generated by Django 4.0.3 on 2022-03-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_player_is_stuff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_stuff',
        ),
        migrations.AlterField(
            model_name='player',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
