# Generated by Django 4.0.3 on 2022-03-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_player_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='ptt',
            new_name='rank_point',
        ),
        migrations.AddField(
            model_name='player',
            name='grade',
            field=models.IntegerField(default=1),
        ),
    ]
