# Generated by Django 4.0.3 on 2022-03-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_rename_ptt_player_rank_point_player_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='selected_role',
            field=models.CharField(default='', max_length=30),
        ),
    ]
