# Generated by Django 4.0.3 on 2022-03-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('song_id', models.IntegerField()),
                ('player_id', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
    ]
