# Generated by Django 4.0.3 on 2022-03-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongInfo',
            fields=[
                ('song_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=100)),
                ('song_author', models.CharField(max_length=100)),
                ('score_author', models.CharField(max_length=100)),
                ('difficulty', models.FloatField(max_length=20)),
                ('level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SongRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('song_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
