# Generated by Django 4.0.3 on 2022-03-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_songinfo_songrecord_delete_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='songinfo',
            name='song_file',
            field=models.FileField(null=True, upload_to='song/'),
        ),
    ]
