# Generated by Django 4.0.3 on 2022-03-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_songinfo_song_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songinfo',
            name='song_file',
            field=models.FileField(null=True, upload_to='song/file/'),
        ),
    ]
