# Generated by Django 4.0.3 on 2022-03-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_alter_songinfo_song_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrecord',
            name='best_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='songrecord',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
